### ISSUE TITLE
Where is the adversarial training of DMBERT?

### ISSUE THREAD

**Issue by gabrer** [THU-KEG/MAVEN-dataset#13]
Just a quick question, as I cannot find the adversarial training in the [DMBERT implementation](https://github.com/THU-KEG/MAVEN-dataset/blob/413f013e88356a3cdeb4c5567994cf9d2a63a9e7/baselines/DMBERT/model.py).

It seems that it's just doing a sentence encoding and classification, without any generator/discriminator mechanism.

Is this implementation different from the one described in the [original](https://github.com/thunlp/Adv-ED/blob/master/BERT/models.py) paper?

Thanks!

**Comment by Bakser** [comment]
Yes. The DMBERT model here is the vanilla baseline without adversarial training (corresponding to `DMBERT` notation in the original paper). The DMBERT with adversarial training (corresponding to `DMBERT+ADV` or `DMBERT+Boot`) is not included in MAVEN experiments since here are in the fully supervised setting rather than the weakly supervised setting.
